<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ApplicationIcon>Assets/WindowIcon.ico</ApplicationIcon>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <Version>1.5.0.0</Version>
        <AssemblyVersion>1.5.0.0</AssemblyVersion>
        <FileVersion>1.5.0.0</FileVersion>
        <Copyright>Copyright © FufuLauncher Development Team</Copyright>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Downloader" Version="5.9.0" />
        <PackageReference Include="ModernWpfUI" Version="0.9.7-preview.2" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
    </ItemGroup>

</Project>