// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AchievementInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FufuLauncher.Services.Yae.Proto {

  /// <summary>Holder for reflection information generated from AchievementInfo.proto</summary>
  public static partial class AchievementInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for AchievementInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AchievementInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVBY2hpZXZlbWVudEluZm8ucHJvdG8igwEKGUFjaGlldmVtZW50UHJvdG9G",
            "aWVsZEluZm8SCgoCaWQYASABKA0SDgoGc3RhdHVzGAIgASgNEhYKDnRvdGFs",
            "X3Byb2dyZXNzGAMgASgNEhgKEGN1cnJlbnRfcHJvZ3Jlc3MYBCABKA0SGAoQ",
            "ZmluaXNoX3RpbWVzdGFtcBgFIAEoDSJQCg9BY2hpZXZlbWVudEl0ZW0SCwoD",
            "cHJlGAEgASgNEg0KBWdyb3VwGAIgASgNEgwKBG5hbWUYAyABKAkSEwoLZGVz",
            "Y3JpcHRpb24YBCABKAki/gEKD01ldGhvZFJ2YUNvbmZpZxIOCgZkb19jbWQY",
            "ASABKA0SGgoSdXBkYXRlX25vcm1hbF9wcm9wGAMgASgNEhIKCm5ld19zdHJp",
            "bmcYBCABKA0SGAoQZmluZF9nYW1lX29iamVjdBgFIAEoDRIbChNldmVudF9z",
            "eXN0ZW1fdXBkYXRlGAYgASgNEh4KFnNpbXVsYXRlX3BvaW50ZXJfY2xpY2sY",
            "ByABKA0SEAoIdG9faW50MzIYCCABKA0SFQoNdGNwX3N0YXRlX3B0chgJIAEo",
            "DRIXCg9zaGFyZWRfaW5mb19wdHIYCiABKA0SEgoKZGVjb21wcmVzcxgLIAEo",
            "DSLTAQoPTmF0aXZlTGliQ29uZmlnEhQKDHN0b3JlX2NtZF9pZBgBIAEoDRIa",
            "ChJhY2hpZXZlbWVudF9jbWRfaWQYAiABKA0SFQoNYXZhdGFyX2NtZF9pZBgD",
            "IAEoDRIzCgptZXRob2RfcnZhGAogAygLMh8uTmF0aXZlTGliQ29uZmlnLk1l",
            "dGhvZFJ2YUVudHJ5GkIKDk1ldGhvZFJ2YUVudHJ5EgsKA2tleRgBIAEoDRIf",
            "CgV2YWx1ZRgCIAEoCzIQLk1ldGhvZFJ2YUNvbmZpZzoCOAEivgIKD0FjaGll",
            "dmVtZW50SW5mbxIPCgd2ZXJzaW9uGAEgASgJEioKBWdyb3VwGAIgAygLMhsu",
            "QWNoaWV2ZW1lbnRJbmZvLkdyb3VwRW50cnkSKgoFaXRlbXMYAyADKAsyGy5B",
            "Y2hpZXZlbWVudEluZm8uSXRlbXNFbnRyeRIrCgdwYl9pbmZvGAQgASgLMhou",
            "QWNoaWV2ZW1lbnRQcm90b0ZpZWxkSW5mbxInCg1uYXRpdmVfY29uZmlnGAUg",
            "ASgLMhAuTmF0aXZlTGliQ29uZmlnGiwKCkdyb3VwRW50cnkSCwoDa2V5GAEg",
            "ASgNEg0KBXZhbHVlGAIgASgJOgI4ARo+CgpJdGVtc0VudHJ5EgsKA2tleRgB",
            "IAEoDRIfCgV2YWx1ZRgCIAEoCzIQLkFjaGlldmVtZW50SXRlbToCOAFCIqoC",
            "H0Z1ZnVMYXVuY2hlci5TZXJ2aWNlcy5ZYWUuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::FufuLauncher.Services.Yae.Proto.AchievementProtoFieldInfo), global::FufuLauncher.Services.Yae.Proto.AchievementProtoFieldInfo.Parser, new[]{ "Id", "Status", "TotalProgress", "CurrentProgress", "FinishTimestamp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FufuLauncher.Services.Yae.Proto.AchievementItem), global::FufuLauncher.Services.Yae.Proto.AchievementItem.Parser, new[]{ "Pre", "Group", "Name", "Description" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FufuLauncher.Services.Yae.Proto.MethodRvaConfig), global::FufuLauncher.Services.Yae.Proto.MethodRvaConfig.Parser, new[]{ "DoCmd", "UpdateNormalProp", "NewString", "FindGameObject", "EventSystemUpdate", "SimulatePointerClick", "ToInt32", "TcpStatePtr", "SharedInfoPtr", "Decompress" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FufuLauncher.Services.Yae.Proto.NativeLibConfig), global::FufuLauncher.Services.Yae.Proto.NativeLibConfig.Parser, new[]{ "StoreCmdId", "AchievementCmdId", "AvatarCmdId", "MethodRva" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::FufuLauncher.Services.Yae.Proto.AchievementInfo), global::FufuLauncher.Services.Yae.Proto.AchievementInfo.Parser, new[]{ "Version", "Group", "Items", "PbInfo", "NativeConfig" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AchievementProtoFieldInfo : pb::IMessage<AchievementProtoFieldInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AchievementProtoFieldInfo> _parser = new pb::MessageParser<AchievementProtoFieldInfo>(() => new AchievementProtoFieldInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AchievementProtoFieldInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FufuLauncher.Services.Yae.Proto.AchievementInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AchievementProtoFieldInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AchievementProtoFieldInfo(AchievementProtoFieldInfo other) : this() {
      id_ = other.id_;
      status_ = other.status_;
      totalProgress_ = other.totalProgress_;
      currentProgress_ = other.currentProgress_;
      finishTimestamp_ = other.finishTimestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AchievementProtoFieldInfo Clone() {
      return new AchievementProtoFieldInfo(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private uint id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private uint status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "total_progress" field.</summary>
    public const int TotalProgressFieldNumber = 3;
    private uint totalProgress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TotalProgress {
      get { return totalProgress_; }
      set {
        totalProgress_ = value;
      }
    }

    /// <summary>Field number for the "current_progress" field.</summary>
    public const int CurrentProgressFieldNumber = 4;
    private uint currentProgress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CurrentProgress {
      get { return currentProgress_; }
      set {
        currentProgress_ = value;
      }
    }

    /// <summary>Field number for the "finish_timestamp" field.</summary>
    public const int FinishTimestampFieldNumber = 5;
    private uint finishTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FinishTimestamp {
      get { return finishTimestamp_; }
      set {
        finishTimestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AchievementProtoFieldInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AchievementProtoFieldInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Status != other.Status) return false;
      if (TotalProgress != other.TotalProgress) return false;
      if (CurrentProgress != other.CurrentProgress) return false;
      if (FinishTimestamp != other.FinishTimestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Status != 0) hash ^= Status.GetHashCode();
      if (TotalProgress != 0) hash ^= TotalProgress.GetHashCode();
      if (CurrentProgress != 0) hash ^= CurrentProgress.GetHashCode();
      if (FinishTimestamp != 0) hash ^= FinishTimestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (Status != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Status);
      }
      if (TotalProgress != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(TotalProgress);
      }
      if (CurrentProgress != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(CurrentProgress);
      }
      if (FinishTimestamp != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(FinishTimestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (Status != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Status);
      }
      if (TotalProgress != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(TotalProgress);
      }
      if (CurrentProgress != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(CurrentProgress);
      }
      if (FinishTimestamp != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(FinishTimestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Status);
      }
      if (TotalProgress != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TotalProgress);
      }
      if (CurrentProgress != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CurrentProgress);
      }
      if (FinishTimestamp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FinishTimestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AchievementProtoFieldInfo other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      if (other.TotalProgress != 0) {
        TotalProgress = other.TotalProgress;
      }
      if (other.CurrentProgress != 0) {
        CurrentProgress = other.CurrentProgress;
      }
      if (other.FinishTimestamp != 0) {
        FinishTimestamp = other.FinishTimestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 16: {
            Status = input.ReadUInt32();
            break;
          }
          case 24: {
            TotalProgress = input.ReadUInt32();
            break;
          }
          case 32: {
            CurrentProgress = input.ReadUInt32();
            break;
          }
          case 40: {
            FinishTimestamp = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 16: {
            Status = input.ReadUInt32();
            break;
          }
          case 24: {
            TotalProgress = input.ReadUInt32();
            break;
          }
          case 32: {
            CurrentProgress = input.ReadUInt32();
            break;
          }
          case 40: {
            FinishTimestamp = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AchievementItem : pb::IMessage<AchievementItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AchievementItem> _parser = new pb::MessageParser<AchievementItem>(() => new AchievementItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AchievementItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FufuLauncher.Services.Yae.Proto.AchievementInfoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AchievementItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AchievementItem(AchievementItem other) : this() {
      pre_ = other.pre_;
      group_ = other.group_;
      name_ = other.name_;
      description_ = other.description_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AchievementItem Clone() {
      return new AchievementItem(this);
    }

    /// <summary>Field number for the "pre" field.</summary>
    public const int PreFieldNumber = 1;
    private uint pre_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Pre {
      get { return pre_; }
      set {
        pre_ = value;
      }
    }

    /// <summary>Field number for the "group" field.</summary>
    public const int GroupFieldNumber = 2;
    private uint group_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Group {
      get { return group_; }
      set {
        group_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 4;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AchievementItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AchievementItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Pre != other.Pre) return false;
      if (Group != other.Group) return false;
      if (Name != other.Name) return false;
      if (Description != other.Description) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Pre != 0) hash ^= Pre.GetHashCode();
      if (Group != 0) hash ^= Group.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Pre != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Pre);
      }
      if (Group != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Group);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Description);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Pre != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Pre);
      }
      if (Group != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Group);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Description);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Pre != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Pre);
      }
      if (Group != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Group);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AchievementItem other) {
      if (other == null) {
        return;
      }
      if (other.Pre != 0) {
        Pre = other.Pre;
      }
      if (other.Group != 0) {
        Group = other.Group;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Pre = input.ReadUInt32();
            break;
          }
          case 16: {
            Group = input.ReadUInt32();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            Description = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Pre = input.ReadUInt32();
            break;
          }
          case 16: {
            Group = input.ReadUInt32();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            Description = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MethodRvaConfig : pb::IMessage<MethodRvaConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MethodRvaConfig> _parser = new pb::MessageParser<MethodRvaConfig>(() => new MethodRvaConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MethodRvaConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FufuLauncher.Services.Yae.Proto.AchievementInfoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MethodRvaConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MethodRvaConfig(MethodRvaConfig other) : this() {
      doCmd_ = other.doCmd_;
      updateNormalProp_ = other.updateNormalProp_;
      newString_ = other.newString_;
      findGameObject_ = other.findGameObject_;
      eventSystemUpdate_ = other.eventSystemUpdate_;
      simulatePointerClick_ = other.simulatePointerClick_;
      toInt32_ = other.toInt32_;
      tcpStatePtr_ = other.tcpStatePtr_;
      sharedInfoPtr_ = other.sharedInfoPtr_;
      decompress_ = other.decompress_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MethodRvaConfig Clone() {
      return new MethodRvaConfig(this);
    }

    /// <summary>Field number for the "do_cmd" field.</summary>
    public const int DoCmdFieldNumber = 1;
    private uint doCmd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DoCmd {
      get { return doCmd_; }
      set {
        doCmd_ = value;
      }
    }

    /// <summary>Field number for the "update_normal_prop" field.</summary>
    public const int UpdateNormalPropFieldNumber = 3;
    private uint updateNormalProp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint UpdateNormalProp {
      get { return updateNormalProp_; }
      set {
        updateNormalProp_ = value;
      }
    }

    /// <summary>Field number for the "new_string" field.</summary>
    public const int NewStringFieldNumber = 4;
    private uint newString_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NewString {
      get { return newString_; }
      set {
        newString_ = value;
      }
    }

    /// <summary>Field number for the "find_game_object" field.</summary>
    public const int FindGameObjectFieldNumber = 5;
    private uint findGameObject_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FindGameObject {
      get { return findGameObject_; }
      set {
        findGameObject_ = value;
      }
    }

    /// <summary>Field number for the "event_system_update" field.</summary>
    public const int EventSystemUpdateFieldNumber = 6;
    private uint eventSystemUpdate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EventSystemUpdate {
      get { return eventSystemUpdate_; }
      set {
        eventSystemUpdate_ = value;
      }
    }

    /// <summary>Field number for the "simulate_pointer_click" field.</summary>
    public const int SimulatePointerClickFieldNumber = 7;
    private uint simulatePointerClick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SimulatePointerClick {
      get { return simulatePointerClick_; }
      set {
        simulatePointerClick_ = value;
      }
    }

    /// <summary>Field number for the "to_int32" field.</summary>
    public const int ToInt32FieldNumber = 8;
    private uint toInt32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ToInt32 {
      get { return toInt32_; }
      set {
        toInt32_ = value;
      }
    }

    /// <summary>Field number for the "tcp_state_ptr" field.</summary>
    public const int TcpStatePtrFieldNumber = 9;
    private uint tcpStatePtr_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TcpStatePtr {
      get { return tcpStatePtr_; }
      set {
        tcpStatePtr_ = value;
      }
    }

    /// <summary>Field number for the "shared_info_ptr" field.</summary>
    public const int SharedInfoPtrFieldNumber = 10;
    private uint sharedInfoPtr_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SharedInfoPtr {
      get { return sharedInfoPtr_; }
      set {
        sharedInfoPtr_ = value;
      }
    }

    /// <summary>Field number for the "decompress" field.</summary>
    public const int DecompressFieldNumber = 11;
    private uint decompress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Decompress {
      get { return decompress_; }
      set {
        decompress_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MethodRvaConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MethodRvaConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DoCmd != other.DoCmd) return false;
      if (UpdateNormalProp != other.UpdateNormalProp) return false;
      if (NewString != other.NewString) return false;
      if (FindGameObject != other.FindGameObject) return false;
      if (EventSystemUpdate != other.EventSystemUpdate) return false;
      if (SimulatePointerClick != other.SimulatePointerClick) return false;
      if (ToInt32 != other.ToInt32) return false;
      if (TcpStatePtr != other.TcpStatePtr) return false;
      if (SharedInfoPtr != other.SharedInfoPtr) return false;
      if (Decompress != other.Decompress) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DoCmd != 0) hash ^= DoCmd.GetHashCode();
      if (UpdateNormalProp != 0) hash ^= UpdateNormalProp.GetHashCode();
      if (NewString != 0) hash ^= NewString.GetHashCode();
      if (FindGameObject != 0) hash ^= FindGameObject.GetHashCode();
      if (EventSystemUpdate != 0) hash ^= EventSystemUpdate.GetHashCode();
      if (SimulatePointerClick != 0) hash ^= SimulatePointerClick.GetHashCode();
      if (ToInt32 != 0) hash ^= ToInt32.GetHashCode();
      if (TcpStatePtr != 0) hash ^= TcpStatePtr.GetHashCode();
      if (SharedInfoPtr != 0) hash ^= SharedInfoPtr.GetHashCode();
      if (Decompress != 0) hash ^= Decompress.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DoCmd != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(DoCmd);
      }
      if (UpdateNormalProp != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(UpdateNormalProp);
      }
      if (NewString != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(NewString);
      }
      if (FindGameObject != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(FindGameObject);
      }
      if (EventSystemUpdate != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(EventSystemUpdate);
      }
      if (SimulatePointerClick != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(SimulatePointerClick);
      }
      if (ToInt32 != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(ToInt32);
      }
      if (TcpStatePtr != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(TcpStatePtr);
      }
      if (SharedInfoPtr != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(SharedInfoPtr);
      }
      if (Decompress != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(Decompress);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DoCmd != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(DoCmd);
      }
      if (UpdateNormalProp != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(UpdateNormalProp);
      }
      if (NewString != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(NewString);
      }
      if (FindGameObject != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(FindGameObject);
      }
      if (EventSystemUpdate != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(EventSystemUpdate);
      }
      if (SimulatePointerClick != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(SimulatePointerClick);
      }
      if (ToInt32 != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(ToInt32);
      }
      if (TcpStatePtr != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(TcpStatePtr);
      }
      if (SharedInfoPtr != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(SharedInfoPtr);
      }
      if (Decompress != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(Decompress);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DoCmd != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DoCmd);
      }
      if (UpdateNormalProp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UpdateNormalProp);
      }
      if (NewString != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NewString);
      }
      if (FindGameObject != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FindGameObject);
      }
      if (EventSystemUpdate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EventSystemUpdate);
      }
      if (SimulatePointerClick != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SimulatePointerClick);
      }
      if (ToInt32 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ToInt32);
      }
      if (TcpStatePtr != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TcpStatePtr);
      }
      if (SharedInfoPtr != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SharedInfoPtr);
      }
      if (Decompress != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Decompress);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MethodRvaConfig other) {
      if (other == null) {
        return;
      }
      if (other.DoCmd != 0) {
        DoCmd = other.DoCmd;
      }
      if (other.UpdateNormalProp != 0) {
        UpdateNormalProp = other.UpdateNormalProp;
      }
      if (other.NewString != 0) {
        NewString = other.NewString;
      }
      if (other.FindGameObject != 0) {
        FindGameObject = other.FindGameObject;
      }
      if (other.EventSystemUpdate != 0) {
        EventSystemUpdate = other.EventSystemUpdate;
      }
      if (other.SimulatePointerClick != 0) {
        SimulatePointerClick = other.SimulatePointerClick;
      }
      if (other.ToInt32 != 0) {
        ToInt32 = other.ToInt32;
      }
      if (other.TcpStatePtr != 0) {
        TcpStatePtr = other.TcpStatePtr;
      }
      if (other.SharedInfoPtr != 0) {
        SharedInfoPtr = other.SharedInfoPtr;
      }
      if (other.Decompress != 0) {
        Decompress = other.Decompress;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DoCmd = input.ReadUInt32();
            break;
          }
          case 24: {
            UpdateNormalProp = input.ReadUInt32();
            break;
          }
          case 32: {
            NewString = input.ReadUInt32();
            break;
          }
          case 40: {
            FindGameObject = input.ReadUInt32();
            break;
          }
          case 48: {
            EventSystemUpdate = input.ReadUInt32();
            break;
          }
          case 56: {
            SimulatePointerClick = input.ReadUInt32();
            break;
          }
          case 64: {
            ToInt32 = input.ReadUInt32();
            break;
          }
          case 72: {
            TcpStatePtr = input.ReadUInt32();
            break;
          }
          case 80: {
            SharedInfoPtr = input.ReadUInt32();
            break;
          }
          case 88: {
            Decompress = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DoCmd = input.ReadUInt32();
            break;
          }
          case 24: {
            UpdateNormalProp = input.ReadUInt32();
            break;
          }
          case 32: {
            NewString = input.ReadUInt32();
            break;
          }
          case 40: {
            FindGameObject = input.ReadUInt32();
            break;
          }
          case 48: {
            EventSystemUpdate = input.ReadUInt32();
            break;
          }
          case 56: {
            SimulatePointerClick = input.ReadUInt32();
            break;
          }
          case 64: {
            ToInt32 = input.ReadUInt32();
            break;
          }
          case 72: {
            TcpStatePtr = input.ReadUInt32();
            break;
          }
          case 80: {
            SharedInfoPtr = input.ReadUInt32();
            break;
          }
          case 88: {
            Decompress = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NativeLibConfig : pb::IMessage<NativeLibConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NativeLibConfig> _parser = new pb::MessageParser<NativeLibConfig>(() => new NativeLibConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NativeLibConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FufuLauncher.Services.Yae.Proto.AchievementInfoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NativeLibConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NativeLibConfig(NativeLibConfig other) : this() {
      storeCmdId_ = other.storeCmdId_;
      achievementCmdId_ = other.achievementCmdId_;
      avatarCmdId_ = other.avatarCmdId_;
      methodRva_ = other.methodRva_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NativeLibConfig Clone() {
      return new NativeLibConfig(this);
    }

    /// <summary>Field number for the "store_cmd_id" field.</summary>
    public const int StoreCmdIdFieldNumber = 1;
    private uint storeCmdId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint StoreCmdId {
      get { return storeCmdId_; }
      set {
        storeCmdId_ = value;
      }
    }

    /// <summary>Field number for the "achievement_cmd_id" field.</summary>
    public const int AchievementCmdIdFieldNumber = 2;
    private uint achievementCmdId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AchievementCmdId {
      get { return achievementCmdId_; }
      set {
        achievementCmdId_ = value;
      }
    }

    /// <summary>Field number for the "avatar_cmd_id" field.</summary>
    public const int AvatarCmdIdFieldNumber = 3;
    private uint avatarCmdId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AvatarCmdId {
      get { return avatarCmdId_; }
      set {
        avatarCmdId_ = value;
      }
    }

    /// <summary>Field number for the "method_rva" field.</summary>
    public const int MethodRvaFieldNumber = 10;
    private static readonly pbc::MapField<uint, global::FufuLauncher.Services.Yae.Proto.MethodRvaConfig>.Codec _map_methodRva_codec
        = new pbc::MapField<uint, global::FufuLauncher.Services.Yae.Proto.MethodRvaConfig>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForMessage(18, global::FufuLauncher.Services.Yae.Proto.MethodRvaConfig.Parser), 82);
    private readonly pbc::MapField<uint, global::FufuLauncher.Services.Yae.Proto.MethodRvaConfig> methodRva_ = new pbc::MapField<uint, global::FufuLauncher.Services.Yae.Proto.MethodRvaConfig>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<uint, global::FufuLauncher.Services.Yae.Proto.MethodRvaConfig> MethodRva {
      get { return methodRva_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NativeLibConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NativeLibConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StoreCmdId != other.StoreCmdId) return false;
      if (AchievementCmdId != other.AchievementCmdId) return false;
      if (AvatarCmdId != other.AvatarCmdId) return false;
      if (!MethodRva.Equals(other.MethodRva)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StoreCmdId != 0) hash ^= StoreCmdId.GetHashCode();
      if (AchievementCmdId != 0) hash ^= AchievementCmdId.GetHashCode();
      if (AvatarCmdId != 0) hash ^= AvatarCmdId.GetHashCode();
      hash ^= MethodRva.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StoreCmdId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(StoreCmdId);
      }
      if (AchievementCmdId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(AchievementCmdId);
      }
      if (AvatarCmdId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(AvatarCmdId);
      }
      methodRva_.WriteTo(output, _map_methodRva_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StoreCmdId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(StoreCmdId);
      }
      if (AchievementCmdId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(AchievementCmdId);
      }
      if (AvatarCmdId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(AvatarCmdId);
      }
      methodRva_.WriteTo(ref output, _map_methodRva_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StoreCmdId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StoreCmdId);
      }
      if (AchievementCmdId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AchievementCmdId);
      }
      if (AvatarCmdId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AvatarCmdId);
      }
      size += methodRva_.CalculateSize(_map_methodRva_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NativeLibConfig other) {
      if (other == null) {
        return;
      }
      if (other.StoreCmdId != 0) {
        StoreCmdId = other.StoreCmdId;
      }
      if (other.AchievementCmdId != 0) {
        AchievementCmdId = other.AchievementCmdId;
      }
      if (other.AvatarCmdId != 0) {
        AvatarCmdId = other.AvatarCmdId;
      }
      methodRva_.MergeFrom(other.methodRva_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StoreCmdId = input.ReadUInt32();
            break;
          }
          case 16: {
            AchievementCmdId = input.ReadUInt32();
            break;
          }
          case 24: {
            AvatarCmdId = input.ReadUInt32();
            break;
          }
          case 82: {
            methodRva_.AddEntriesFrom(input, _map_methodRva_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StoreCmdId = input.ReadUInt32();
            break;
          }
          case 16: {
            AchievementCmdId = input.ReadUInt32();
            break;
          }
          case 24: {
            AvatarCmdId = input.ReadUInt32();
            break;
          }
          case 82: {
            methodRva_.AddEntriesFrom(ref input, _map_methodRva_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AchievementInfo : pb::IMessage<AchievementInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AchievementInfo> _parser = new pb::MessageParser<AchievementInfo>(() => new AchievementInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AchievementInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FufuLauncher.Services.Yae.Proto.AchievementInfoReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AchievementInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AchievementInfo(AchievementInfo other) : this() {
      version_ = other.version_;
      group_ = other.group_.Clone();
      items_ = other.items_.Clone();
      pbInfo_ = other.pbInfo_ != null ? other.pbInfo_.Clone() : null;
      nativeConfig_ = other.nativeConfig_ != null ? other.nativeConfig_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AchievementInfo Clone() {
      return new AchievementInfo(this);
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 1;
    private string version_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Version {
      get { return version_; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "group" field.</summary>
    public const int GroupFieldNumber = 2;
    private static readonly pbc::MapField<uint, string>.Codec _map_group_codec
        = new pbc::MapField<uint, string>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForString(18, ""), 18);
    private readonly pbc::MapField<uint, string> group_ = new pbc::MapField<uint, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<uint, string> Group {
      get { return group_; }
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 3;
    private static readonly pbc::MapField<uint, global::FufuLauncher.Services.Yae.Proto.AchievementItem>.Codec _map_items_codec
        = new pbc::MapField<uint, global::FufuLauncher.Services.Yae.Proto.AchievementItem>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForMessage(18, global::FufuLauncher.Services.Yae.Proto.AchievementItem.Parser), 26);
    private readonly pbc::MapField<uint, global::FufuLauncher.Services.Yae.Proto.AchievementItem> items_ = new pbc::MapField<uint, global::FufuLauncher.Services.Yae.Proto.AchievementItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<uint, global::FufuLauncher.Services.Yae.Proto.AchievementItem> Items {
      get { return items_; }
    }

    /// <summary>Field number for the "pb_info" field.</summary>
    public const int PbInfoFieldNumber = 4;
    private global::FufuLauncher.Services.Yae.Proto.AchievementProtoFieldInfo pbInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::FufuLauncher.Services.Yae.Proto.AchievementProtoFieldInfo PbInfo {
      get { return pbInfo_; }
      set {
        pbInfo_ = value;
      }
    }

    /// <summary>Field number for the "native_config" field.</summary>
    public const int NativeConfigFieldNumber = 5;
    private global::FufuLauncher.Services.Yae.Proto.NativeLibConfig nativeConfig_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::FufuLauncher.Services.Yae.Proto.NativeLibConfig NativeConfig {
      get { return nativeConfig_; }
      set {
        nativeConfig_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AchievementInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AchievementInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Version != other.Version) return false;
      if (!Group.Equals(other.Group)) return false;
      if (!Items.Equals(other.Items)) return false;
      if (!object.Equals(PbInfo, other.PbInfo)) return false;
      if (!object.Equals(NativeConfig, other.NativeConfig)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Version.Length != 0) hash ^= Version.GetHashCode();
      hash ^= Group.GetHashCode();
      hash ^= Items.GetHashCode();
      if (pbInfo_ != null) hash ^= PbInfo.GetHashCode();
      if (nativeConfig_ != null) hash ^= NativeConfig.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Version.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Version);
      }
      group_.WriteTo(output, _map_group_codec);
      items_.WriteTo(output, _map_items_codec);
      if (pbInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(PbInfo);
      }
      if (nativeConfig_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(NativeConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Version.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Version);
      }
      group_.WriteTo(ref output, _map_group_codec);
      items_.WriteTo(ref output, _map_items_codec);
      if (pbInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(PbInfo);
      }
      if (nativeConfig_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(NativeConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Version.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      size += group_.CalculateSize(_map_group_codec);
      size += items_.CalculateSize(_map_items_codec);
      if (pbInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PbInfo);
      }
      if (nativeConfig_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NativeConfig);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AchievementInfo other) {
      if (other == null) {
        return;
      }
      if (other.Version.Length != 0) {
        Version = other.Version;
      }
      group_.MergeFrom(other.group_);
      items_.MergeFrom(other.items_);
      if (other.pbInfo_ != null) {
        if (pbInfo_ == null) {
          PbInfo = new global::FufuLauncher.Services.Yae.Proto.AchievementProtoFieldInfo();
        }
        PbInfo.MergeFrom(other.PbInfo);
      }
      if (other.nativeConfig_ != null) {
        if (nativeConfig_ == null) {
          NativeConfig = new global::FufuLauncher.Services.Yae.Proto.NativeLibConfig();
        }
        NativeConfig.MergeFrom(other.NativeConfig);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Version = input.ReadString();
            break;
          }
          case 18: {
            group_.AddEntriesFrom(input, _map_group_codec);
            break;
          }
          case 26: {
            items_.AddEntriesFrom(input, _map_items_codec);
            break;
          }
          case 34: {
            if (pbInfo_ == null) {
              PbInfo = new global::FufuLauncher.Services.Yae.Proto.AchievementProtoFieldInfo();
            }
            input.ReadMessage(PbInfo);
            break;
          }
          case 42: {
            if (nativeConfig_ == null) {
              NativeConfig = new global::FufuLauncher.Services.Yae.Proto.NativeLibConfig();
            }
            input.ReadMessage(NativeConfig);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Version = input.ReadString();
            break;
          }
          case 18: {
            group_.AddEntriesFrom(ref input, _map_group_codec);
            break;
          }
          case 26: {
            items_.AddEntriesFrom(ref input, _map_items_codec);
            break;
          }
          case 34: {
            if (pbInfo_ == null) {
              PbInfo = new global::FufuLauncher.Services.Yae.Proto.AchievementProtoFieldInfo();
            }
            input.ReadMessage(PbInfo);
            break;
          }
          case 42: {
            if (nativeConfig_ == null) {
              NativeConfig = new global::FufuLauncher.Services.Yae.Proto.NativeLibConfig();
            }
            input.ReadMessage(NativeConfig);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
