<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
        <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
        <ApplicationIcon>Assets/WindowIcon.ico</ApplicationIcon>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <Platforms>x86;x64;arm64</Platforms>
        <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
        <PublishProfile>Properties\PublishProfiles\win-$(Platform).pubxml</PublishProfile>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <UseWinUI>true</UseWinUI>

        <EnableMsixTooling>true</EnableMsixTooling>
        <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>

        <WindowsPackageType>None</WindowsPackageType>

        <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>

        <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>

        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

        <PublishSingleFile>true</PublishSingleFile>

        <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>

        <PublishReadyToRun>true</PublishReadyToRun>

        <Version>1.6.0.3</Version>
        <AssemblyVersion>1.6.0.3</AssemblyVersion>
        <FileVersion>1.6.0.3</FileVersion>
        <Copyright>Copyright © FufuLauncher Development Team</Copyright>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />
    </ItemGroup>

    <ItemGroup>
        <Manifest Include="$(ApplicationManifest)" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="CommunityToolkit.WinUI.UI.Controls.Markdown" Version="7.1.2" />
        <PackageReference Include="Google.Protobuf" Version="3.35.1" />
        <PackageReference Include="H.NotifyIcon.WinUI" Version="2.2.0" />
        <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
        <PackageReference Include="InputSimulatorPlus" Version="1.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.28" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.28">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
        <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.2.4" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
        <PackageReference Include="Microsoft.Graphics.Win2D" Version="1.4.0" />
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4078.44" />
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
        <PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="3.0.1" />
    <PackageReference Include="MoonSharp" Version="2.0.0" />
    <PackageReference Include="MoonSharp.Interpreter.netcore" Version="3.0.2" />
        <PackageReference Include="PuppeteerSharp" Version="25.3.1" />
        <PackageReference Include="QRCoder" Version="1.8.0" />
        <PackageReference Include="QuestPDF" Version="2026.7.1" />
        <PackageReference Include="Sentry" Version="6.6.0" />
        <PackageReference Include="Sentry.Profiling" Version="6.6.0" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
        <PackageReference Include="System.Diagnostics.EventLog" Version="8.0.2" />
        <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="8.0.1" />
        <PackageReference Include="System.Drawing.Common" Version="9.0.17" />
        <PackageReference Include="System.IO.Hashing" Version="9.0.11" />
        <PackageReference Include="System.Management" Version="8.0.0" />
        <PackageReference Include="WinUIEx" Version="2.9.1" />
        <PackageReference Include="YamlDotNet" Version="18.1.0" />
        <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\FufuLauncher\Update.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <Link>Update.json</Link>
        </Content>
        <Content Include="Strings\en-US\Resources.resw" />
        <Content Include="Strings\zh-CN\Resources.resw" />
        <Content Include="Strings\fr-FR\Resources.resw" />
        <Content Include="Strings\de-DE\Resources.resw" />
        <Content Include="Strings\ru-RU\Resources.resw" />
        <Content Include="Strings\ja-JP\Resources.resw" />
        <Content Include="Strings\es-ES\Resources.resw" />
        <Content Include="Strings\zh-TW\Resources.resw" />
        <Content Include="Strings\ko-KR\Resources.resw" />
        <Content Include="Strings\it-IT\Resources.resw" />
        <Content Include="Strings\id-ID\Resources.resw" />
        <Content Include="Strings\pt-BR\Resources.resw" />
        <Content Include="Strings\es-MX\Resources.resw" />
        <Content Remove="Plugins\Avatar\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="protobuf-net" Version="3.2.56" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Remove="Plugins\Avatar\**" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Plugins\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Assets\HelpGifs\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Assets\Flags\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Assets\Backpack\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Assets\mirrors.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    
    <ItemGroup>
        <Compile Remove="Models\GameConfig.cs" />
        <Compile Update="Views\Model\BrowserConfig.cs">
            <DependentUpon>BrowserWindow.xaml</DependentUpon>
        </Compile>
        <Compile Remove="Plugins\Avatar\**" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Constants\MiHoYo\" />
      <Folder Include="Services\MiHoYo\Fingerprint\" />
      <Folder Include="Services\UID\" />
    </ItemGroup>

    <ItemGroup>
      <Page Remove="Plugins\Avatar\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Plugins\Avatar\**" />
    </ItemGroup>

    <ItemGroup>
      <Resource Remove="Plugins\Avatar\**" />
    </ItemGroup>

    <Target Name="RemoveUnwantedRuntimesFolders" AfterTargets="Build;Publish" Condition="Exists('$(OutDir)runtimes')">
        <ItemGroup>
            <AllRuntimeDirs Include="$([System.IO.Directory]::GetDirectories('$(OutDir)runtimes'))" />
            <WinRuntimeDirs Include="$([System.IO.Directory]::GetDirectories('$(OutDir)runtimes', 'win*'))" />
            <RuntimeDirsToDelete Include="@(AllRuntimeDirs)" Exclude="@(WinRuntimeDirs)" />
        </ItemGroup>

        <RemoveDir Directories="@(RuntimeDirsToDelete)" />
        <Message Text="已清理runtimes文件夹" Importance="high" />
    </Target>
</Project>